// App.vue

<template>
  <div class="phoenix-app">
    <!-- 侧边栏 -->
    <aside class="sidebar">
      <div class="brand">
        <div class="logo-circle">
          <div class="diamond"></div>
        </div>
        <div class="brand-text">
          <span class="main">Bank of China</span>
          <span class="sub">中国银行贵金属</span>
        </div>
      </div>
      
      <nav class="menu">
        <div 
          v-for="item in menuItems" 
          :key="item.id"
          :class="['menu-item', { active: activeTab === item.id }]"
          @click="activeTab = item.id"
        >
          <i :class="item.icon"></i>
          <span>{{ item.label }}</span>
        </div>
      </nav>

      <div class="sidebar-footer">
        <p>© 2025 BANK OF CHINA</p>
        <p>V2.0 STABLE</p>
      </div>
    </aside>

    <!-- 主体 -->
    <main class="main-content">
      <header class="top-bar">
        <div class="left">
          <div class="vault-status">
            <i class="el-icon-location-outline"></i>
            <span>BOC MAIN VAULT (CN)</span>
          </div>
          <el-input 
            prefix-icon="el-icon-search" 
            placeholder="快速检索业务流水..." 
            size="small"
            class="search-input"
          ></el-input>
        </div>
        
        <div class="right">
          <div class="system-status">
            <span class="dot pulse"></span>
            GLOBAL LINK ACTIVE
          </div>
          <el-badge is-dot class="notice">
            <i class="el-icon-bell"></i>
          </el-badge>
          <div class="user-profile">
            <div class="user-info">
              <span class="name">James Wilson</span>
              <span class="role">CHIEF STRATEGIST</span>
            </div>
            <el-avatar shape="square" :size="36" src="https://picsum.photos/seed/userBOC/100"></el-avatar>
          </div>
        </div>
      </header>

      <div class="page-container">
        <component :is="activeTabComponent"></component>
      </div>
    </main>

    <!-- 2FA 安全弹窗 -->
    <el-dialog
      title="身份安全校验"
      :visible.sync="show2FA"
      width="400px"
      custom-class="boc-dialog"
      center
    >
      <div class="dialog-content">
        <div class="security-icon">
          <i class="el-icon-lock"></i>
        </div>
        <p class="desc">请通过中国银行企业网银证书进行二次验证</p>
        <el-form label-position="top">
          <el-form-item label="交易密码">
            <el-input type="password" show-password placeholder="请输入交易密码"></el-input>
          </el-form-item>
          <el-form-item label="动态口令 (E-Token)">
            <div class="otp-inputs">
              <el-input v-for="i in 6" :key="i" maxlength="1" size="medium"></el-input>
            </div>
          </el-form-item>
        </el-form>
      </div>
      <span slot="footer" class="dialog-footer">
        <el-button @click="show2FA = false" size="medium">取消</el-button>
        <el-button type="primary" @click="show2FA = false" size="medium" class="boc-btn-red">授权任务</el-button>
      </span>
    </el-dialog>

    <button class="fab-lock" @click="show2FA = true">
      <i class="el-icon-lock"></i>
    </button>
  </div>
</template>

<script>
import Dashboard from './components/Dashboard.vue';
import Transfers from './components/Transfers.vue';
import Inventory from './components/Inventory.vue';

export default {
  components: { Dashboard, Transfers, Inventory },
  data() {
    return {
      activeTab: 'DASHBOARD',
      show2FA: false,
      menuItems: [
        { id: 'DASHBOARD', label: '工作台首页', icon: 'el-icon-s-home' },
        { id: 'ACCOUNTS', label: '账户概览', icon: 'el-icon-bank-card' },
        { id: 'TRANSFERS', label: '转账清算', icon: 'el-icon-refresh' },
        { id: 'INVENTORY', label: '库存管理', icon: 'el-icon-box' },
        { id: 'PROJECTION', label: '远期预测', icon: 'el-icon-data-line' },
        { id: 'MAILBOX', label: '消息中心', icon: 'el-icon-message' },
      ]
    };
  },
  computed: {
    activeTabComponent() {
      if (this.activeTab === 'DASHBOARD') return 'Dashboard';
      if (this.activeTab === 'TRANSFERS') return 'Transfers';
      if (this.activeTab === 'INVENTORY') return 'Inventory';
      return { render: h => h('div', { class: 'under-construction' }, [
        h('i', { class: 'el-icon-setting' }),
        h('p', '功能开发中...')
      ])};
    }
  }
}
</script>

<style lang="scss">
/* Phoenix SCSS 设计规范 */
$boc-red: #B6002A;
$slate-dark: #1E293B;
$slate-light: #F8FAFC;
$text-main: #334155;
$text-sub: #94A3B8;
$radius-main: 12px;
$shadow-soft: 0 4px 20px rgba(0,0,0,0.05);

.phoenix-app {
  display: flex;
  height: 100vh;
  overflow: hidden;
  color: $text-main;
}

/* 侧边栏样式 */
.sidebar {
  width: 240px;
  background: $slate-dark;
  color: white;
  display: flex;
  flex-direction: column;
  padding: 0;
  
  .brand {
    padding: 24px;
    display: flex;
    align-items: center;
    gap: 12px;
    border-bottom: 1px solid rgba(255,255,255,0.05);
    
    .logo-circle {
      width: 36px;
      height: 36px;
      background: $boc-red;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      .diamond {
        width: 14px;
        height: 14px;
        background: white;
        transform: rotate(45deg);
      }
    }
    
    .brand-text {
      display: flex;
      flex-direction: column;
      .main { font-weight: 900; font-size: 14px; letter-spacing: -0.5px; text-transform: uppercase; }
      .sub { font-size: 10px; color: $text-sub; font-weight: bold; margin-top: 2px; }
    }
  }

  .menu {
    flex: 1;
    padding: 20px 12px;
    
    .menu-item {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 14px 16px;
      border-radius: 10px;
      cursor: pointer;
      transition: all 0.3s;
      color: #94a3b8;
      font-size: 14px;
      font-weight: 500;
      margin-bottom: 4px;
      
      &:hover { background: rgba(255,255,255,0.05); color: white; }
      &.active {
        background: $boc-red;
        color: white;
        box-shadow: 0 10px 15px -3px rgba(182, 0, 42, 0.25);
      }
      
      i { font-size: 18px; }
    }
  }

  .sidebar-footer {
    padding: 20px;
    font-size: 10px;
    color: rgba(255,255,255,0.2);
    font-weight: 900;
    letter-spacing: 2px;
    border-top: 1px solid rgba(255,255,255,0.05);
  }
}

/* 主内容区 */
.main-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  background: $slate-light;
  overflow-y: auto;
}

.top-bar {
  height: 64px;
  background: white;
  border-bottom: 1px solid #eef2f6;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 32px;
  position: sticky;
  top: 0;
  z-index: 100;

  .left {
    display: flex;
    align-items: center;
    gap: 24px;
    
    .vault-status {
      font-size: 11px;
      font-weight: 900;
      color: $text-sub;
      letter-spacing: 1px;
      display: flex;
      align-items: center;
      gap: 6px;
      i { font-size: 14px; color: $boc-red; }
    }
    
    .search-input { width: 300px; .el-input__inner { border-radius: 10px; background: #f1f5f9; border: none; } }
  }

  .right {
    display: flex;
    align-items: center;
    gap: 24px;
    
    .system-status {
      font-size: 10px;
      font-weight: 900;
      color: $text-sub;
      background: #f1f5f9;
      padding: 6px 12px;
      border-radius: 6px;
      display: flex;
      align-items: center;
      gap: 8px;
      
      .dot { width: 6px; height: 6px; background: #10b981; border-radius: 50%; }
      .pulse { animation: statusPulse 2s infinite; }
    }

    .notice { cursor: pointer; color: $text-sub; font-size: 20px; &:hover { color: $boc-red; } }

    .user-profile {
      display: flex;
      align-items: center;
      gap: 12px;
      padding-left: 20px;
      border-left: 1px solid #eef2f6;
      
      .user-info {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        .name { font-size: 12px; font-weight: bold; }
        .role { font-size: 9px; color: $boc-red; font-weight: 900; letter-spacing: 1px; margin-top: 2px; }
      }
    }
  }
}

.page-container { padding: 32px; max-width: 1400px; margin: 0 auto; width: 100%; box-sizing: border-box; }

/* 2FA Dialog 深度定制 */
.boc-dialog {
  border-radius: 20px;
  .el-dialog__header { background: $boc-red; padding: 30px; .el-dialog__title { color: white; font-weight: 900; text-transform: uppercase; letter-spacing: 2px; } .el-dialog__close { color: white; } }
  .dialog-content {
    text-align: center;
    .security-icon { font-size: 40px; color: $boc-red; margin-bottom: 16px; }
    .desc { font-size: 12px; color: $text-sub; font-weight: bold; margin-bottom: 24px; text-transform: uppercase; }
    .otp-inputs { display: flex; gap: 8px; justify-content: center; .el-input { width: 42px; .el-input__inner { text-align: center; font-weight: bold; } } }
  }
  .boc-btn-red { background: $boc-red; border: none; font-weight: bold; letter-spacing: 1px; &:hover { opacity: 0.9; } }
}

.fab-lock {
  position: fixed;
  bottom: 40px;
  right: 40px;
  width: 56px;
  height: 56px;
  background: $boc-red;
  color: white;
  border-radius: 16px;
  border: 4px solid white;
  box-shadow: 0 10px 30px rgba(182, 0, 42, 0.4);
  cursor: pointer;
  z-index: 1000;
  font-size: 20px;
  transition: all 0.3s;
  &:hover { transform: translateY(-5px) scale(1.05); }
}

@keyframes statusPulse {
  0% { box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.4); }
  70% { box-shadow: 0 0 0 6px rgba(16, 185, 129, 0); }
  100% { box-shadow: 0 0 0 0 rgba(16, 185, 129, 0); }
}

.under-construction {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 60vh;
  color: $text-sub;
  i { font-size: 48px; margin-bottom: 16px; }
  p { font-weight: 900; letter-spacing: 2px; text-transform: uppercase; }
}
</style>

// App.tsx

import React, { useState } from 'react';
import { TabType } from './types';
import Sidebar from './components/Sidebar';
import Dashboard from './components/Dashboard';
import Transfers from './components/Transfers';
import Inventory from './components/Inventory';
import { 
  Bell, 
  Search, 
  ChevronDown,
  Lock,
  RefreshCw,
  Globe
} from 'lucide-react';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabType>(TabType.DASHBOARD);
  const [is2FAModalOpen, setIs2FAModalOpen] = useState(false);

  const renderContent = () => {
    switch (activeTab) {
      case TabType.DASHBOARD:
        return <Dashboard />;
      case TabType.TRANSFERS:
        return <Transfers />;
      case TabType.INVENTORY:
        return <Inventory />;
      case TabType.ACCOUNTS:
      case TabType.PROJECTION:
      case TabType.STATEMENTS:
      case TabType.MAILBOX:
        return (
          <div className="flex flex-col items-center justify-center h-[60vh] text-slate-400 space-y-4">
            <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center">
              <Lock size={32} />
            </div>
            <div className="text-center">
              <h3 className="text-sm font-black text-slate-800 uppercase tracking-widest">{activeTab} MODULE UNDER CONSTRUCTION</h3>
              <p className="text-[10px] font-bold text-slate-400 mt-2 uppercase tracking-tight">此功能在当前原型阶段暂未开放，请查看仪表盘或库存管理页面。</p>
            </div>
          </div>
        );
      default:
        return <Dashboard />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex selection:bg-[#B6002A]/10 selection:text-[#B6002A]">
      {/* 侧边导航 */}
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />

      {/* 主内容区 */}
      <main className="flex-1 ml-64 min-h-screen flex flex-col">
        {/* 顶部工具栏 */}
        <header className="h-16 bg-white border-b border-slate-100 flex items-center justify-between px-8 sticky top-0 z-40">
          <div className="flex items-center gap-6 w-1/2">
            <div className="flex items-center gap-2 text-slate-400 hover:text-[#B6002A] cursor-pointer transition-colors group">
              <Globe size={18} className="group-hover:rotate-12 transition-transform" />
              <span className="text-[10px] font-black tracking-[0.2em] uppercase">CN / BOC Main Vault</span>
              <ChevronDown size={14} />
            </div>
            <div className="relative w-full max-w-sm">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <input 
                type="text" 
                placeholder="快速检索业务流水或指令..." 
                className="w-full pl-11 pr-4 py-2.5 bg-slate-50 border border-slate-100 rounded-xl text-[10px] font-bold focus:outline-none focus:ring-4 focus:ring-[#B6002A]/5 focus:border-[#B6002A]/20 transition-all uppercase tracking-tight"
              />
            </div>
          </div>

          <div className="flex items-center gap-6">
            <div className="flex items-center gap-2 text-[9px] font-black text-slate-500 bg-slate-50 px-3 py-1.5 rounded-lg border border-slate-100">
              <RefreshCw size={10} className="text-[#B6002A] animate-spin-slow" />
              <span className="uppercase tracking-widest">Global Link Active</span>
            </div>
            
            <button className="relative p-2 text-slate-400 hover:text-slate-800 transition-colors">
              <Bell size={18} />
              <span className="absolute top-2 right-2 w-1.5 h-1.5 bg-[#B6002A] rounded-full ring-2 ring-white"></span>
            </button>

            <div className="h-6 w-px bg-slate-100"></div>

            <button className="flex items-center gap-3 group">
              <div className="flex flex-col items-end">
                <span className="text-xs font-black text-slate-800 leading-none">James Wilson</span>
                <span className="text-[8px] text-[#B6002A] font-black tracking-[0.2em] uppercase mt-1">Chief Strategist</span>
              </div>
              <div className="w-9 h-9 rounded-xl bg-slate-900 border-2 border-white shadow-lg overflow-hidden group-hover:border-[#B6002A]/20 transition-all">
                <img src="https://picsum.photos/seed/userBOC/100" alt="Avatar" className="w-full h-full object-cover" />
              </div>
            </button>
          </div>
        </header>

        {/* 核心内容 */}
        <div className="p-8 max-w-[1400px] mx-auto w-full flex-1">
          {renderContent()}
        </div>

        {/* 底部状态栏 */}
        <footer className="px-8 py-5 border-t border-slate-100 flex justify-between items-center text-[9px] text-slate-400 font-black uppercase tracking-[0.3em] bg-white">
          <div className="flex gap-8">
            <a href="#" className="hover:text-[#B6002A]">Compliance</a>
            <a href="#" className="hover:text-[#B6002A]">Security Center</a>
            <a href="#" className="hover:text-[#B6002A]">System Health</a>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-green-500">Global Infrastructure Online</span>
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse shadow-sm"></div>
          </div>
        </footer>
      </main>

      {/* 2FA 验证弹窗适配 */}
      {is2FAModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/40 backdrop-blur-md p-4 animate-in fade-in duration-300">
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-300 border border-slate-100">
            <div className="bg-[#B6002A] p-10 flex flex-col items-center text-white relative">
              <div className="absolute top-0 left-0 w-full h-full opacity-10 pointer-events-none overflow-hidden">
                 <div className="w-96 h-96 border-[40px] border-white rounded-full -mt-24 -ml-24"></div>
              </div>
              <div className="w-16 h-16 bg-white/20 rounded-2xl flex items-center justify-center mb-6 backdrop-blur-md shadow-inner">
                <Lock size={32} />
              </div>
              <h2 className="text-2xl font-black uppercase tracking-widest text-center">Identity Verification</h2>
              <p className="text-white/70 text-[10px] font-bold mt-3 text-center uppercase tracking-[0.2em]">请通过中国银行企业网银证书或移动 CA 进行二次验证</p>
            </div>
            <div className="p-10 space-y-8 bg-white">
              <div className="space-y-3">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Transaction Password</label>
                <input 
                  type="password" 
                  className="w-full px-4 py-3.5 bg-slate-50 border border-slate-200 rounded-2xl focus:outline-none focus:ring-4 focus:ring-[#B6002A]/5 focus:border-[#B6002A]/30 transition-all font-mono placeholder:text-slate-300"
                  placeholder="请输入您的 8-16 位交易密码"
                />
              </div>
              <div className="space-y-3">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">E-Token / SMS OTP</label>
                <div className="grid grid-cols-6 gap-2">
                  {[1, 2, 3, 4, 5, 6].map((i) => (
                    <input 
                      key={i} 
                      type="text" 
                      maxLength={1} 
                      className="w-full h-14 text-center text-xl font-black bg-slate-50 border border-slate-200 rounded-2xl focus:outline-none focus:ring-4 focus:ring-[#B6002A]/5 focus:border-[#B6002A]/30 transition-all"
                    />
                  ))}
                </div>
              </div>
              <div className="flex gap-4 pt-6">
                <button 
                  onClick={() => setIs2FAModalOpen(false)}
                  className="flex-1 py-4 text-slate-400 font-black text-[10px] uppercase tracking-[0.2em] hover:text-slate-800 transition-colors"
                >
                  Cancel
                </button>
                <button 
                  onClick={() => setIs2FAModalOpen(false)}
                  className="flex-[2] py-4 bg-[#B6002A] text-white rounded-2xl font-black text-[10px] uppercase tracking-[0.3em] hover:bg-[#960022] shadow-xl shadow-[#B6002A]/30 transition-all active:scale-95"
                >
                  Authorize Task
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 2FA 浮动按钮 */}
      <button 
        onClick={() => setIs2FAModalOpen(true)}
        className="fixed bottom-10 right-10 w-16 h-16 bg-[#B6002A] text-white rounded-2xl flex items-center justify-center shadow-2xl hover:scale-110 active:scale-95 transition-all z-50 group border-4 border-white"
      >
        <Lock size={22} className="group-hover:rotate-12 transition-transform" />
      </button>

      <style>{`
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .animate-spin-slow {
          animation: spin-slow 12s linear infinite;
        }
        body {
          font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          letter-spacing: -0.01em;
        }
      `}</style>
    </div>
  );
};

export default App;
